version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_aerolinea
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
